version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: acorn
    versions:
    - ">= 7.a, < 8"
  - dependency-name: "@babel/register"
    versions:
    - "> 7.7.4"
  - dependency-name: jest-cli
    versions:
    - "> 24.9.0"
  - dependency-name: "@storybook/addon-actions"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: typesafe-actions
    versions:
    - ">= 5.a, < 6"
  - dependency-name: "@types/webpack"
    versions:
    - 4.41.26
    - 5.0.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.31
    - 14.14.33
    - 14.14.34
    - 14.14.37
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@wordpress/components"
    versions:
    - 12.0.2
    - 12.0.5
    - 12.0.6
    - 12.0.7
  - dependency-name: "@types/puppeteer"
    versions:
    - 5.4.2
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
