// @flow
// flow-typed signature: b5f7135e4a485e6707c022a968cf43da
// flow-typed version: <<STUB>>/brookjs_v^0.11.11/flow_v0.69.0

import type { Middleware } from 'redux';
import type { Observable } from 'kefir';

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brookjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'brookjs' {
    declare type Delta<A, S> = (actions$: Observable<A>, state$: Observable<S>) => Observable<A>;
    declare function observeDelta<A, S>(...Delta<A ,S>): Middleware<S, A>;

    declare module.exports: any;
}
