// @flow
// flow-typed signature: a7efc2132d1372a49030d63057179563
// flow-typed version: <<STUB>>/brookjs-desalinate_v^0.11.10/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brookjs-desalinate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'brookjs-desalinate' {
  declare module.exports: any;
}
