// @flow
// flow-typed signature: 3274e27d259b374039227bb6a3a32e2d
// flow-typed version: <<STUB>>/brookjs-cli_v^0.11.11/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brookjs-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'brookjs-cli' {
  declare module.exports: any;
}
