// @flow
// flow-typed signature: ae3af1dc77b39748a24b255bc6704a5a
// flow-typed version: <<STUB>>/jss-nested_v^6.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-nested'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-nested' {
  declare module.exports: any;
}
