// @flow
// flow-typed signature: 8a00827df30cf07bf07c18e57cc76caa
// flow-typed version: <<STUB>>/prismjs_v1.15.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prismjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prismjs' {
  declare module.exports: any;
}
