// @flow
// flow-typed signature: 021d41fc29ba74ea14d11ac6673b93d4
// flow-typed version: <<STUB>>/react-jss_v^8.2.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-jss' {
  declare module.exports: any;
}
