// @flow
// flow-typed signature: 9e76d3a8efca2395324ce719bc12644a
// flow-typed version: <<STUB>>/sheet-router_v^4.0.0-0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sheet-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sheet-router' {
  declare module.exports: any;
}
