// @flow
// flow-typed signature: 8afeb86d6e34b88a4318c3a67404bf1b
// flow-typed version: <<STUB>>/sinon_v^6.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon' {
  declare module.exports: any;
}
