// @flow
// flow-typed signature: 4922260ad368410d749c288de4fd50af
// flow-typed version: <<STUB>>/sprintf-js_v^1.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sprintf-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sprintf-js' {
  declare module.exports: any;
}
